---
# Copyright 2016, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure etcd data directory exists
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: "etcd"
    group: "etcd"
    mode: "0755"
  tags:
    - etcd-config

- name: Set etcd access method (http/https)
  set_fact: etcd_access_method="{% if etcd_user_ssl_cert is defined and etcd_user_ssl_key is defined  %}https{% else %}http{% endif %}"
  run_once: true
  tags:
    - etcd-config
    - etcd-verify

- name: Drop etcd upstart configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Reload init scripts
    - Restart etcd
  with_items:
    - { src: "etcd.conf.j2", dest: "/etc/init/etcd.conf" }
    - { src: "etcd.override.j2", dest: "/etc/init/etcd.override" }
  tags:
    - etcd-config
    - upstart-init
    - etcd-init

- name: Start etcd and add to boot services
  service:
   name: "etcd"
   enabled: yes
  tags:
    - upstart-init
    - etcd-init

- name: Flush handlers
  meta: flush_handlers

- name: Verify etcd cluster health
  shell: "etcdctl cluster-health"
  register: etcd_health
  failed_when: etcd_health.rc != 0
  until: etcd_health|success
  retries: 5
  delay: 2
  when: inventory_hostname == groups[etcd_cluster_group][0]
  tags:
    - etcd-config
    - etcd-verify
