---
# Copyright 2016, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add etcd apt-keys
  apt_key:
    id: "{{ item.hash_id }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    data: "{{ item.data | default(omit) }}"
    state: "present"
  with_items: etcd_gpg_keys
  register: add_keys
  until: add_keys|success
  retries: 5
  delay: 2
  tags:
    - etcd-apt-keys

- name: Add etcd apt-keys using fallback keyserver
  apt_key:
    id: "{{ item.hash_id }}"
    keyserver: "{{ item.fallback_keyserver }}"
    state: "present"
  register: add_keys_fallback
  until: add_keys_fallback|success
  retries: 5
  delay: 2
  with_items: etcd_gpg_keys
  when: add_keys|failed and item.fallback_keyserver is defined
  tags:
    - etcd-apt-keys

- name: Drop calico repo pin
  template:
    src: "projectcalico_pin.pref.j2"
    dest: "/etc/apt/preferences.d/projectcalico_pin.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - etcd-repo-pin

- name: Add calico repo(s)
  apt_repository:
    repo: "{{ calico_apt_repo.repo }}"
    state: "{{ calico_apt_repo.state }}"
  register: add_repos
  until: add_repos|success
  retries: 5
  delay: 2
  tags:
    - etcd-repos
