---

- name: Playbook for role testing
  hosts: all
  roles:
    - config_template
    - role: "{{ playbook_dir | dirname | dirname | basename }}"
  vars:
    etcd_local_address: "{{ inventory_hostname }}"

- name: Attempt a partial deployment of the role only
  hosts: all[0]
  roles:
    - config_template
    - role: "{{ playbook_dir | dirname | dirname | basename }}"

- name: Verify the role functions
  hosts: all
  tasks:
    - name: Check etcd is running
      command: pgrep -a etcd
      register: etcd_proc
      changed_when: false
    - name: Test etcd cluster health
      command: etcdctl cluster-health
      register: etcd_health
      changed_when: false
    - name: Check role functions
      assert:
        that:
          - "'cluster is healthy' in etcd_health.stdout"
      changed_when: false
